- import_playbook: prerequisites.yml

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - base
    - { role: system76, when: ansible_system_vendor == 'System76' }
    - dev
    - browser
    - fun
