- name: Install Brave
  command: 'yay -S --noconfirm --needed --cleanafter {{ item.package }}'
  with_items:
    - { package: 'brave-bin' }

- name: Create Brave initial_preferences.json file (version <= 87)
  become: yes
  copy:
    src: files/brave_initial_preferences.json
    dest: /usr/lib/brave-bin/master_preferences

- name: Create Brave initial_preferences.json file
  become: yes
  copy:
    src: files/brave_initial_preferences.json
    dest: /usr/lib/brave-bin/initial_preferences.json

- name: Launch Brave
  shell: brave {{ brave_extensions_urls|join(' ') }} &>/dev/null &
  environment:
    DISPLAY: ':0'
